version: '3'  # version of compose format

services:
  dashboard-app:
    container_name: dashboard-app
    build:
      context: .
      dockerfile: Dockerfile
    image: dashboardapp:v2
    environment:
      TZ: America/Toronto
    ports:
      - 8501:8501
